const requireTest = rule => (data, path) =>
  require(rule)(data, path);

module.exports = {
  account: requireTest('./SchemaRules/Account'),
  activity: requireTest('./SchemaRules/Activity'),
  actor: requireTest('./SchemaRules/Actor'),
  agent: requireTest('./SchemaRules/Agent'),
  attachment: requireTest('./SchemaRules/Attachment'),
  authority: requireTest('./SchemaRules/Authority'),
  boolean: requireTest('./Values/boolean'),
  context: requireTest('./SchemaRules/Context'),
  definition: requireTest('./SchemaRules/Definition'),
  duration: requireTest('./RegexValues/Duration'),
  extensions: requireTest('./Maps/extensions'),
  float: requireTest('./Values/float'),
  group: requireTest('./SchemaRules/Group'),
  imt: requireTest('./RegexValues/Imt'),
  integer: requireTest('./Values/integer'),
  interactionComponent: requireTest('./SchemaRules/InteractionComponent'),
  interactionType: requireTest('./RegexValues/InteractionType'),
  iri: requireTest('./RegexValues/Iri'),
  language: requireTest('./RegexValues/Language'),
  languageMap: requireTest('./Maps/languageMap'),
  mailto: requireTest('./RegexValues/Mailto'),
  object: requireTest('./SchemaRules/Object'),
  result: requireTest('./SchemaRules/Result'),
  scaled: requireTest('./Values/scaled'),
  sha1: requireTest('./RegexValues/Sha1'),
  statement: requireTest('./SchemaRules/Statement'),
  statementRef: requireTest('./SchemaRules/StatementRef'),
  string: requireTest('./Values/string'),
  subStatement: requireTest('./SchemaRules/SubStatement'),
  timestamp: requireTest('./RegexValues/Timestamp'),
  uuid: requireTest('./RegexValues/Uuid'),
  verb: requireTest('./SchemaRules/Verb'),
  version: requireTest('./RegexValues/Version'),
};
