import Test from './Helpers/Test';

const requireTest = (rule: string) => (test: Test): void =>
  require(rule).default(test);

export const account = requireTest('./SchemaRules/Account');
export const activity = requireTest('./SchemaRules/Activity');
export const actor = requireTest('./SchemaRules/Actor');
export const agent = requireTest('./SchemaRules/Agent');
export const attachment = requireTest('./SchemaRules/Attachment');
export const authority = requireTest('./SchemaRules/Authority');
export const booleanValue = requireTest('./Values/Boolean');
export const context = requireTest('./SchemaRules/Context');
export const contextActivities = requireTest('./SchemaRules/ContextActivities');
export const definition = requireTest('./SchemaRules/Definition');
export const duration = requireTest('./RegexValues/Duration');
export const extensions = requireTest('./Maps/Extensions');
export const group = requireTest('./SchemaRules/Group');
export const subGroup = requireTest('./SchemaRules/SubGroup');
export const imt = requireTest('./RegexValues/Imt');
export const integerValue = requireTest('./Values/Integer');
export const interactionComponent = requireTest('./SchemaRules/InteractionComponent');
export const interactionType = requireTest('./RegexValues/InteractionType');
export const iri = requireTest('./RegexValues/Iri');
export const language = requireTest('./RegexValues/Language');
export const languageMap = requireTest('./Maps/LanguageMap');
export const mailto = requireTest('./RegexValues/Mailto');
export const numberValue = requireTest('./Values/Number');
export const object = requireTest('./SchemaRules/Object');
export const result = requireTest('./SchemaRules/Result');
export const scaledValue = requireTest('./Values/Scaled');
export const score = requireTest('./SchemaRules/Score');
export const sha1 = requireTest('./RegexValues/Sha1');
export const statement = requireTest('./SchemaRules/Statement');
export const statementRef = requireTest('./SchemaRules/StatementRef');
export const stringValue = requireTest('./Values/String');
export const subStatement = requireTest('./SchemaRules/SubStatement');
export const subStatementObject = requireTest('./SchemaRules/SubStatementObject');
export const timestamp = requireTest('./RegexValues/Timestamp');
export const uuid = requireTest('./RegexValues/Uuid');
export const verb = requireTest('./SchemaRules/Verb');
export const version = requireTest('./RegexValues/Version');
